// AUTO-GENERATED by scripts/generate-presets.mjs — do not edit by hand.
// Regenerate: node scripts/generate-presets.mjs
// Ready-made, level 1–3 character builds for the "Ready-Made" creation mode. Each 'draft' is a
// complete BuilderDraft partial (merged over defaults by builder.applyDraft).
import type { BuilderDraft } from '@/character-builder/builderStore'

export interface CharacterPreset {
  id: string
  title: string
  charName: string
  subtitle: string
  blurb: string
  level: number
  primaryAbility: string
  primaryStat: string
  isSpellcaster: boolean
  draft: Partial<BuilderDraft>
}

export const PRESETS: CharacterPreset[] = [
  {
    "id": "half-orc-berserker",
    "title": "The Berserker",
    "charName": "Grosh",
    "subtitle": "Half-Orc Barbarian · Level 3",
    "blurb": "A towering half-orc who answers every problem with fury and a greataxe. Rage first, ask questions never.",
    "level": 3,
    "primaryAbility": "Strength",
    "primaryStat": "str",
    "isSpellcaster": false,
    "draft": {
      "name": "Grosh",
      "level": 3,
      "classIndex": "barbarian",
      "className": "Barbarian",
      "classEdition": "2014",
      "classHitDie": 12,
      "classSpellcastingAbility": null,
      "classSkillChoices": 2,
      "classSkillOptions": [
        "animal-handling",
        "athletics",
        "intimidation",
        "nature",
        "perception",
        "survival"
      ],
      "availableSubclasses": [
        {
          "index": "berserker",
          "name": "Berserker"
        }
      ],
      "subclassIndex": "berserker",
      "subclassName": "Path of the Berserker",
      "raceIndex": "half-orc",
      "raceName": "Half-Orc",
      "raceEdition": "2014",
      "raceSpeed": 30,
      "raceSizeCategory": "Medium",
      "raceAbilityBonuses": {
        "str": 2,
        "con": 1
      },
      "raceLanguageCount": 2,
      "raceAutoLanguages": [
        "common",
        "orc"
      ],
      "raceLanguageChoices": 0,
      "backgroundIndex": "custom",
      "backgroundName": "Outlander",
      "backgroundEdition": "2014",
      "backgroundSkillProficiencies": [
        "survival",
        "perception"
      ],
      "abilityMethod": "manual",
      "baseScores": {
        "str": 15,
        "con": 14,
        "dex": 13,
        "wis": 12,
        "int": 10,
        "cha": 8
      },
      "selectedSkills": [
        "athletics",
        "intimidation"
      ],
      "expertiseSkills": [],
      "selectedLanguages": [
        "common",
        "orc"
      ],
      "levelChoices": {},
      "selectedCantrips": [],
      "selectedSpells": [],
      "currentStep": 1
    }
  },
  {
    "id": "human-vanguard",
    "title": "The Vanguard",
    "charName": "Aldric",
    "subtitle": "Human Fighter · Level 1",
    "blurb": "A disciplined human soldier who holds the line. Sword, shield, and an unbreakable Defense.",
    "level": 1,
    "primaryAbility": "Strength",
    "primaryStat": "str",
    "isSpellcaster": false,
    "draft": {
      "name": "Aldric",
      "level": 1,
      "classIndex": "fighter",
      "className": "Fighter",
      "classEdition": "2014",
      "classHitDie": 10,
      "classSpellcastingAbility": null,
      "classSkillChoices": 2,
      "classSkillOptions": [
        "acrobatics",
        "animal-handling",
        "athletics",
        "history",
        "insight",
        "intimidation",
        "perception",
        "survival"
      ],
      "availableSubclasses": [],
      "subclassIndex": "",
      "subclassName": "",
      "raceIndex": "human",
      "raceName": "Human",
      "raceEdition": "2014",
      "raceSpeed": 30,
      "raceSizeCategory": "Medium",
      "raceAbilityBonuses": {
        "str": 1,
        "dex": 1,
        "con": 1,
        "int": 1,
        "wis": 1,
        "cha": 1
      },
      "raceLanguageCount": 1,
      "raceAutoLanguages": [
        "common"
      ],
      "raceLanguageChoices": 1,
      "backgroundIndex": "custom",
      "backgroundName": "Soldier",
      "backgroundEdition": "2014",
      "backgroundSkillProficiencies": [
        "survival",
        "intimidation"
      ],
      "abilityMethod": "manual",
      "baseScores": {
        "str": 15,
        "con": 14,
        "dex": 13,
        "wis": 12,
        "int": 10,
        "cha": 8
      },
      "selectedSkills": [
        "athletics",
        "perception"
      ],
      "expertiseSkills": [],
      "selectedLanguages": [
        "common",
        "dwarvish"
      ],
      "levelChoices": {
        "1": {
          "fighting-style": "defense"
        }
      },
      "selectedCantrips": [],
      "selectedSpells": [],
      "currentStep": 1
    }
  },
  {
    "id": "tiefling-shadow",
    "title": "The Shadow",
    "charName": "Vesper",
    "subtitle": "Tiefling Rogue · Level 1",
    "blurb": "A silver-tongued tiefling who thrives in the dark — picking locks, pockets, and fights on their own terms.",
    "level": 1,
    "primaryAbility": "Dexterity",
    "primaryStat": "dex",
    "isSpellcaster": false,
    "draft": {
      "name": "Vesper",
      "level": 1,
      "classIndex": "rogue",
      "className": "Rogue",
      "classEdition": "2014",
      "classHitDie": 8,
      "classSpellcastingAbility": null,
      "classSkillChoices": 4,
      "classSkillOptions": [
        "acrobatics",
        "athletics",
        "deception",
        "insight",
        "intimidation",
        "investigation",
        "perception",
        "performance",
        "persuasion",
        "sleight-of-hand",
        "stealth"
      ],
      "availableSubclasses": [],
      "subclassIndex": "",
      "subclassName": "",
      "raceIndex": "tiefling",
      "raceName": "Tiefling",
      "raceEdition": "2014",
      "raceSpeed": 30,
      "raceSizeCategory": "Medium",
      "raceAbilityBonuses": {
        "int": 1,
        "cha": 2
      },
      "raceLanguageCount": 2,
      "raceAutoLanguages": [
        "common",
        "infernal"
      ],
      "raceLanguageChoices": 0,
      "backgroundIndex": "custom",
      "backgroundName": "Charlatan",
      "backgroundEdition": "2014",
      "backgroundSkillProficiencies": [
        "deception",
        "sleight-of-hand"
      ],
      "abilityMethod": "manual",
      "baseScores": {
        "dex": 15,
        "con": 14,
        "int": 13,
        "wis": 12,
        "cha": 10,
        "str": 8
      },
      "selectedSkills": [
        "stealth",
        "perception",
        "acrobatics",
        "investigation"
      ],
      "expertiseSkills": [
        "stealth",
        "perception"
      ],
      "selectedLanguages": [
        "common",
        "infernal"
      ],
      "levelChoices": {},
      "selectedCantrips": [],
      "selectedSpells": [],
      "currentStep": 1
    }
  },
  {
    "id": "dragonborn-oathsworn",
    "title": "The Oathsworn",
    "charName": "Rhogar",
    "subtitle": "Dragonborn Paladin · Level 1",
    "blurb": "A dragonborn paladin bound by a sacred oath, smiting the wicked with radiant steel and unshakeable resolve.",
    "level": 1,
    "primaryAbility": "Strength",
    "primaryStat": "str",
    "isSpellcaster": true,
    "draft": {
      "name": "Rhogar",
      "level": 1,
      "classIndex": "paladin",
      "className": "Paladin",
      "classEdition": "2014",
      "classHitDie": 10,
      "classSpellcastingAbility": "cha",
      "classSkillChoices": 2,
      "classSkillOptions": [
        "athletics",
        "insight",
        "intimidation",
        "medicine",
        "persuasion",
        "religion"
      ],
      "availableSubclasses": [],
      "subclassIndex": "",
      "subclassName": "",
      "raceIndex": "dragonborn",
      "raceName": "Dragonborn",
      "raceEdition": "2014",
      "raceSpeed": 30,
      "raceSizeCategory": "Medium",
      "raceAbilityBonuses": {
        "str": 2,
        "cha": 1
      },
      "raceLanguageCount": 2,
      "raceAutoLanguages": [
        "common",
        "draconic"
      ],
      "raceLanguageChoices": 0,
      "backgroundIndex": "custom",
      "backgroundName": "Acolyte",
      "backgroundEdition": "2014",
      "backgroundSkillProficiencies": [
        "insight",
        "religion"
      ],
      "abilityMethod": "manual",
      "baseScores": {
        "str": 15,
        "cha": 14,
        "con": 13,
        "wis": 12,
        "int": 10,
        "dex": 8
      },
      "selectedSkills": [
        "athletics",
        "intimidation"
      ],
      "expertiseSkills": [],
      "selectedLanguages": [
        "common",
        "draconic"
      ],
      "levelChoices": {},
      "selectedCantrips": [],
      "selectedSpells": [],
      "currentStep": 1
    }
  },
  {
    "id": "human-ascetic",
    "title": "The Ascetic",
    "charName": "Mei",
    "subtitle": "Human Monk · Level 2",
    "blurb": "A human monk who turned discipline into a weapon. Strikes like water — swift, flowing, and impossible to hold.",
    "level": 2,
    "primaryAbility": "Dexterity",
    "primaryStat": "dex",
    "isSpellcaster": false,
    "draft": {
      "name": "Mei",
      "level": 2,
      "classIndex": "monk",
      "className": "Monk",
      "classEdition": "2014",
      "classHitDie": 8,
      "classSpellcastingAbility": null,
      "classSkillChoices": 2,
      "classSkillOptions": [
        "acrobatics",
        "athletics",
        "history",
        "insight",
        "religion",
        "stealth"
      ],
      "availableSubclasses": [],
      "subclassIndex": "",
      "subclassName": "",
      "raceIndex": "human",
      "raceName": "Human",
      "raceEdition": "2014",
      "raceSpeed": 30,
      "raceSizeCategory": "Medium",
      "raceAbilityBonuses": {
        "str": 1,
        "dex": 1,
        "con": 1,
        "int": 1,
        "wis": 1,
        "cha": 1
      },
      "raceLanguageCount": 1,
      "raceAutoLanguages": [
        "common"
      ],
      "raceLanguageChoices": 1,
      "backgroundIndex": "custom",
      "backgroundName": "Hermit",
      "backgroundEdition": "2014",
      "backgroundSkillProficiencies": [
        "medicine",
        "religion"
      ],
      "abilityMethod": "manual",
      "baseScores": {
        "dex": 15,
        "wis": 14,
        "con": 13,
        "str": 12,
        "int": 10,
        "cha": 8
      },
      "selectedSkills": [
        "acrobatics",
        "stealth"
      ],
      "expertiseSkills": [],
      "selectedLanguages": [
        "common",
        "celestial"
      ],
      "levelChoices": {},
      "selectedCantrips": [],
      "selectedSpells": [],
      "currentStep": 1
    }
  },
  {
    "id": "tiefling-evoker",
    "title": "The Evoker",
    "charName": "Ignis",
    "subtitle": "Tiefling Wizard · Level 1",
    "blurb": "A tiefling wizard with fire in their blood and their spellbook. Six spells memorized, endless ambition.",
    "level": 1,
    "primaryAbility": "Intelligence",
    "primaryStat": "int",
    "isSpellcaster": true,
    "draft": {
      "name": "Ignis",
      "level": 1,
      "classIndex": "wizard",
      "className": "Wizard",
      "classEdition": "2014",
      "classHitDie": 6,
      "classSpellcastingAbility": "int",
      "classSkillChoices": 2,
      "classSkillOptions": [
        "arcana",
        "history",
        "insight",
        "investigation",
        "medicine",
        "religion"
      ],
      "availableSubclasses": [],
      "subclassIndex": "",
      "subclassName": "",
      "raceIndex": "tiefling",
      "raceName": "Tiefling",
      "raceEdition": "2014",
      "raceSpeed": 30,
      "raceSizeCategory": "Medium",
      "raceAbilityBonuses": {
        "int": 1,
        "cha": 2
      },
      "raceLanguageCount": 2,
      "raceAutoLanguages": [
        "common",
        "infernal"
      ],
      "raceLanguageChoices": 0,
      "backgroundIndex": "custom",
      "backgroundName": "Sage",
      "backgroundEdition": "2014",
      "backgroundSkillProficiencies": [
        "history",
        "insight"
      ],
      "abilityMethod": "manual",
      "baseScores": {
        "int": 15,
        "con": 14,
        "dex": 13,
        "wis": 12,
        "cha": 10,
        "str": 8
      },
      "selectedSkills": [
        "arcana",
        "investigation"
      ],
      "expertiseSkills": [],
      "selectedLanguages": [
        "common",
        "infernal"
      ],
      "levelChoices": {},
      "selectedCantrips": [
        {
          "index": "fire-bolt",
          "name": "Fire Bolt"
        },
        {
          "index": "mage-hand",
          "name": "Mage Hand"
        },
        {
          "index": "prestidigitation",
          "name": "Prestidigitation"
        }
      ],
      "selectedSpells": [
        {
          "index": "magic-missile",
          "name": "Magic Missile",
          "level": 1
        },
        {
          "index": "shield",
          "name": "Shield",
          "level": 1
        },
        {
          "index": "mage-armor",
          "name": "Mage Armor",
          "level": 1
        },
        {
          "index": "detect-magic",
          "name": "Detect Magic",
          "level": 1
        },
        {
          "index": "burning-hands",
          "name": "Burning Hands",
          "level": 1
        },
        {
          "index": "sleep",
          "name": "Sleep",
          "level": 1
        }
      ],
      "currentStep": 1
    }
  }
]
